### ISSUE TITLE
Fix tt:div/xml:lang indent

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#11]
For [`tt:div/xml:lang`](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt.xsd#L205), the current indentation is shown wrong by some editors (depending on the set tab size), as here spaces have been used instead of tabs.

**Comment by nigelmegitt** [comment]
My usual preference is to set my editor to expand tabs to be spaces - I'm not sure what I did here, but agree it should be consistent.

**Comment by nigelmegitt** [comment]
Due to copy/paste and editor behaviour, the fix for this accidentally found its way into #23.

**Comment by nigelmegitt** [comment]
Closing since #23 is merged.
