### ISSUE TITLE
tts:padding regex issue

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#13]
The [regular expression for `tts:padding`](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt_datatypes.xsd#L135) is not entirely correct and allows to omit the actual numbers, while the corresponding units are still present. So e.g. a value of `% % % %` passes the XSD validation.

Thus it would make sense to align the affected regex with other datatypes' regexes that are as well based on `<length>`. This will also ease to compare the different regexes. See e.g. [`pixelOriginType`](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt_datatypes.xsd#L124) (`\d*(\.\d+)?` vs. `\d*\.?\d+` as part of the numerical value).

**Comment by nigelmegitt** [comment]
Great spot @spoeschel ! There was another problem too, which is that the numbers were wrongly permitted to be negative. I will fix to use the regex:

```
[+]?\d*\.?\d+(px|c|%)(\s([+]?\d*\.?\d+(px|c|%)))?(\s([+]?\d*\.?\d+(px|c|%)))?(\s([+]?\d*\.?\d+(px|c|%)))?
``` 

which more closely matches those used for the other length values, as you suggest.
