### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#15]
A [default value for the `ttp:cellResolution` attribute](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/parameter.xsd#L82) is set but not for other attributes (e.g. `tts:fontSize`).

**Comment by nigelmegitt** [comment]
This seems to match the specification text for `ttp:cellResolution` in Tech3350 v1.2:

> The `ttp:cellResolution` should be set explicitly. Otherwise the default value of "32 15" shall apply.

there is no equivalent statement for any other attribute in the specification. However Annex B does list the applicable initial values. I think this issue can be closed with no change, and if necessary a spec issue can be raised with EBU - do you agree @spoeschel ?

**Comment by spoeschel** [comment]
Indeed, for other attributes the default is only listed in Annex B. So I agree to close here.
