### ISSUE TITLE
Different units with tts:origin/tts:extent

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#16]
According to the XSD the attributes `tts:origin` and `tts:extent` are not allowed to use different units in the same value e.g. the value `"20px 40%"` is forbidden. However TTML1 does not impose such limitation (for `tts:fontSize` in contrast, it does; the XSD implements this case correctly).

I slightly recall that we had a similar discussion during the development of TTML2/IMSC1 if I remember correcty. But I neither remember the result nor do I find the issue or e-mail thread.

**Comment by nigelmegitt** [comment]
I can't see any restriction in TTML1 or EBU-TT Part 1 either, so the XSD should allow for mixed units.
