### ISSUE TITLE
Datatype (re)definitions in Part 1

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#17]
Currently the [Part 1 repo](https://github.com/ebu/ebu-tt-xsd) and the [Part M repo](https://github.com/ebu/ebu-tt-m-xsd) share a common set of EBU-TT datatypes that are all defined in both repos. Extending this set however [can/will lead to issues](https://github.com/ebu/ebu-tt-m-xsd/pull/15#pullrequestreview-250959621). 

Therefore datatypes that are only used by Part M should not be (re)defined by Part 1. As far as I can see, this only affects `ebuttdt:noTimezoneDateType` which is only used by Part M.

**Comment by spoeschel** [comment]
(see also https://github.com/ebu/ebu-tt-m-xsd/issues/25)

**Comment by nigelmegitt** [comment]
Unrequired datatypes for Part M will be removed from ebu-tt-m-xsd by merging ebu/ebu-tt-m-xsd#28.
