### ISSUE TITLE
limitedClockTimingType allows out-of-range hour value

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#2]
The `limitedClockTimingType` type corresponds to the "Limited-Full-Clock-Value" in § 4.14 of Tech 3350 v1.2. The [current regex](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt_datatypes.xsd#L170) however allows to specify an hour value that is out of the defined range (`0` to `23`), e.g. `50`.

**Comment by nigelmegitt** [comment]
There seems to be a bug in the spec here - the `clockTimingType` is restricted to having an integer number of seconds, but the type is used on, e.g. `begin` attributes where fractional seconds values are sometimes needed and completely reasonable.

My plan is to fix the hours part only to restrict it to 00-23.

**Comment by nigelmegitt** [comment]
I've opened an (internal EBU) bug on the spec regarding the fractions of seconds component.

**Comment by spoeschel** [comment]
Hmm, Part 1, § 4.14 already says:
```
A Limited-Full-Clock-Value shall have the format hh:mm:ss and may be followed by an optional
decimal fraction to denote fractional seconds.
```

**Comment by nigelmegitt** [comment]
True, maybe there's no issue here after all, though I think the spec could be clearer.
