### ISSUE TITLE
fullClockTimingType allows leap second

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#3]
The `fullClockTimingType` type corresponds to the "Full-Clock-value" in § 4.13 of Tech 3350 v1.2, which is used for media time expressions. The [current regex](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt_datatypes.xsd#L180) however allows to specify the value `60` for leap seconds, which would only make sense for a clock time expression.

**Comment by nigelmegitt** [comment]
The spec does not restrict the values of the seconds component, but I agree @spoeschel that there's no sensible case for seconds values > 59.

**Comment by spoeschel** [comment]
Indead; the spec has to explicit restriction here (in contrast to clock time).

**Comment by andreastai** [comment]
The use of the value of `60` seconds has been introduced in later versions of EBU-TT Part 1 on request. It also reflects what is defined in the time expression section of TTML. Therefore (at least for the moment) this should not be changed.

**Comment by nigelmegitt** [comment]
[TTML1](https://www.w3.org/TR/ttml1/#timing-value-timeExpression) says:
> Except when `ttp:timeBase` is `clock` and `ttp:clockMode` is `local` or `utc`, use of the special value of 60 seconds to denote a leap second is undefined and should not be used.

I can see that 60s values are permitted in Tech3350 v1.2 for `clockTimingType` but it is silent about the constraint on `mediaTimingType`.

Possibly a specification issue is needed here, but on balance I think we should reject documents with media timing types that have 60 in the seconds component.

**Comment by andreastai** [comment]
@nigelmegitt @spoeschel Clearly there is a strict recommendation not to use "60" for the second part as it does not apply to a time expression when the timebase is set to "media". But the keywords SHALL NOT do not apply. As stated in other issues from my view, the schema should be scoped to SHALL and SHALL NOT constraints.  

Althought Part 1 has TTML 1 as reference we can see in TTML2 what the direction of the referenced standard is. In section 12.3.1 the corresponding section where you took the citation is as follows:

> Minutes are constrained to [0…59], while seconds (including any fractional part) are constrained to the closed interval [0,60], where the value 60 applies only to leap seconds. Except when ttp:timeBase is clock and ttp:clockMode is local or utc, use of the special value of 60 seconds to denote a leap second is deprecated. When performing presentation processing, the appearance of this special value in other time bases or clock modes must be interpreted as if the value 59 had been specified.

On the one hand '60' s for other time bases are deprecated but on the other hand presentation processors are given a clear guideline how to handle such cases. I infer from this part also that they shall process and not reject documents that make use of this deprecated combinations.

**Comment by spoeschel** [comment]
Hmm, it is indeed not forbidden in the spec, actually. In that case, it is OK for me to leave it unmodified.

**Comment by nigelmegitt** [comment]
This is certainly in the category of things where a validation system that can generate warnings should do so. Possibly the approach we take here depends on the conclusion to ebu/ebu-tt-m-xsd#26 - if we do end up offering a "stricter than the spec" option for validation as well as an "accurate to the spec" one, then this would be a candidate for inclusion in the "stricter than the spec" one, and we should leave it as permitted in the "accurate to the spec" XSD.

**Comment by spoeschel** [comment]
I would say it is a weaker candidate for such a possible "stricter than the spec" XSD, compared to the ebu/ebu-tt-m-xsd#26 findings:

For the latter findings, it will be possible to state that (certainly) all "should" constraints are covered, compared to the "accurate to the spec" XSD. In the current case (which is a single issue, rather found by accident), it will currently just be an additional (possible) issue that has been fixed (or rather an addressed aspect that is currently not covered by the spec at all). But it will not be possible to claim that a (further) class of errors/ambiguities has been addressed.

**Comment by nigelmegitt** [comment]
@spoeschel @tairt trying to think of a way forward - should we do _nothing_ here for now and @spoeschel would you like to raise a spec issue in EBU to say "don't allow 60s values in _media_ times?" - if that request is adopted then we can apply the constraint here.

**Comment by andreastai** [comment]
I think we shoud leave it as is for now. This is from my view a TTML issue and the changed text between TTML1 and TTML2 is indication that the TTWG is aware of this constellation. As there is also no known problem with the specification as is, I recommend to close the issue and the corresponding PR.

**Comment by spoeschel** [comment]
This sounds reasonable to me.

**Comment by nigelmegitt** [comment]
OK I'm happy to do nothing here for now then, and if the specification changes we can take action.

> there is also no known problem with the specification as is

@tairt just for the record, I don't share that view - it may not be logged and agreed as a problem, but this issue right here indicates there is a problem with the specification.

Closing as per the above discussion.
