### ISSUE TITLE
tt:br doesn't allow @ttm:agent

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#5]
According to TTML, the [`tt:br` element](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt.xsd#L332) allows "any attribute in TT Metadata namespace". This includes also the attribute `@ttm:agent`, which is currently not allowed by the XSD on this element.

[it is of course questionable whether it makes sense to use this attribute here, but technically it is allowed there]

**Comment by nigelmegitt** [comment]
Just for posterity, Tech3350 v1.2 §2.2 says
> Attributes in the TTML metadata namespace ("http://www.w3.org/ns/ttml#metadata") may appear on any TTML element where TTML 1 permits the use of attributes in that namespace. The content models of the elements `tt:body`, `tt:div`, `tt:p`, `tt:span` and `tt:br` allow the use of attributes in the TTML metadata namespace.

TTML1 [says](https://www.w3.org/TR/ttml1/#content-vocabulary-br) `br` can contain:
> `{any attribute in TT Metadata namespace}`

And that namespace includes the attributes `ttm:agent` and `ttm:role` so both of those should be permitted on `br`.
