### ISSUE TITLE
Unneeded maxOccurs="1"

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-xsd#9]
The element `tt:br` [specifies](https://github.com/ebu/ebu-tt-xsd/blob/214fdc3a6a2a0c91e22cd69a8d9b69a031b68b2a/ebutt.xsd#L337) `maxOccurs="1"` for the `tt:metadata` child element, which is the default and should therefore be removed for readability and consistency with other attribute definitions.

**Comment by nigelmegitt** [comment]
See also https://github.com/ebu/ebu-tt-m-xsd/issues/10#issuecomment-502695788

**Comment by nigelmegitt** [comment]
The decision for ebu-tt-m-xsd is that if _either_ the `minOccurs` or the `maxOccurs` is not the default of 1, then _both_ should be specified. In #22 I applied this rule and added a style guide note to the README, so this is consistent. Does #22 close this issue for you @spoeschel ?

**Comment by spoeschel** [comment]
Yes, #22 addresses this issue. Thank you!

**Comment by nigelmegitt** [comment]
Thank you, in that case I can close this.
